reference_defs = {
    'COM': "Composer.",
    'COA': "Attributed composer.",
    'COS': "Suspected composer.",
    'COL': "Composer's abbreviated, alias, or stage name.",
    'COC': "Composer(s) corporate name.",
    'CDT': "Composer's dates.",
    'CNT': "Nationality of the composer.",
    'LYR': "Lyricist.",
    'LIB': "Librettist.",
    'LAR': "Arranger.",
    'LOR': "Orchestrator.",
    'TXO': "Original language of vocal/choral text.",
    'TXL': "Language of the",
    'TRN': "Translator of text.",
    'RTL': "Title of album.",
    'RMM': "Manufacturer or sponsoring company.",
    'RC#': "Recording company's catalogue number.",
    'RRD': "Date of release.",
    'RLC': "Place of recording.",
    'RNP': "Name of the producer.",
    'RDT': "Date of recording.",
    'RT#': "Track number.",
    'MPN': "Performer's name.",
    'MPS': "Suspected performer.",
    'MRD': "Date of performance.",
    'MLC': "Place of performance.",
    'MCN': "Name of the conductor of the performance.",
    'MPD': "Date of first performance.",
    'OTL': "Title.",
    'XEN': "Translated title (in English).",
    'XFR': "Translated title (in French).",
    'XDE': "Translated title (in German).",
    'XNI': "Translated title (in Japanese).",
    'OTP': "Popular Title.",
    'OTA': "Alternative title.",
    'OPR': "Title of larger (or parent) work from which the encoded piece is a part.",
    'OAC': "Act number.",
    'OSC': "Scene number.",
    'OMV': "Movement number.",
    'OMD': "Movement designation or movement name.",
    'OPS': "Opus number.",
    'ONM': "Number.",
    'OVM': "Volume.",
    'ODE': "Dedication.",
    'OCO': "Commission.",
    'OCL': "Collector.",
    'ONB': "Free format note related to the title or identity of the encoded work.",
    'ODT': "Date of composition.",
    'OCY': "Country of composition.",
    'OPC': "City, town or village of composition.",
    'GTL': "Group Title.",
    'GAW': "Associated Work.",
    'GCO': "Collection designation.",
    'PUB': "Publication status.",
    'PPR': "First publisher.",
    'PDT': "Date first published.",
    'PPP': "Place first published.",
    'PC#': "Publisher's catalogue number.",
    'SCT': "Scholarly catalogue abbreviation and number.",
    'SCA': "Scholarly catalogue (unabbreviated) name.",
    'SMS': "Manuscript source name.",
    'SML': "Manuscript location.",
    'SMA': "Acknowledgement of manuscript access.",
    'YEP': "Publisher of electronic edition.",
    'YEC': "Date and owner of electronic copyright.",
    'YER': "Date electronic edition released.",
    'YEM': "Copyright message.",
    'YEN': "Country of copyright.",
    'YOR': "Original document.",
    'YOO': "Original document owner.",
    'YOY': "Original copyright year.",
    'YOE': "Original editor.",
    'EED': "Electronic Editor.",
    'ENC': "Encoder of the electronic document.",
    'EMD': "Document modification description.",
    'EEV': "Electronic edition version.",
    'EFL': "File number.",
    'EST': "Encoding status.",
    'VTS': "Checksum validation number.",
    'ACO': "Collection designation.",
    'AFR': "Form designation.",
    'AGN': "Genre designation.",
    'AST': "Style, period, or type of work designation.",
    'AMD': "Mode Classification.",
    'AMT': "Metric Classification.",
    'AIN': "Instrumentation.",
    'ARE': "Geographical region of origin.",
    'ARL': "Geographical location of origin.",
    'HAO': "Aural History.",
    'HTX': "Free-form Translation of Vocal Text.",
    'RLN': "ASCII language setting.",
    'RDF': "User-defined signifiers.",
    'RDT': "Date encoded.",
    'RNB': "Representation note.",
    'RWG': "Representation warning.",
}
